### ISSUE TITLE
Fenton 2013

### ISSUE THREAD

**Issue by dnzmarcio** [jhchou/peditools#1]
I have been looking to implement in R the online calculator (https://peditools.org/fenton2013/index.php) which is based on a growth chart from Fenton et al. 2013. The reference paper (https://pubmed.ncbi.nlm.nih.gov/32012066/) for the online calculator refers to this R-package.  Although the growth chart from Fenton et al. 2003 is available, the growth chart from Fenton et al 2013 is not available yet. They somewhat differ from each other. 

What would be the steps to include Fenton et al 2013?

**Comment by jhchou** [comment]
At the time of publication, the LMS parameters for the Fenton 2013 preterm growth chart were not public and were only available from Tanis Fenton by license. The great news is that as of Feb 2020, the LMS data is available for non-commercial use, but you will have to contact her directly; see her web page under "Research or Individual use": https://live-ucalgary.ucalgary.ca/resource/preterm-growth-chart/preterm-growth-chart

I anticipated this would be an issue for the R PediTools package and included a function add_lmsdata() that allows you to add LMS parameters for other charts. The file has to be in a rather specific format though (you can see in the sysdata.Rda LMS data file here).

I did provide Tanis Fenton with a CSV file of the Fenton 2013 LMS parameters in the correct format, so if you contact her, you can ask whether she still has it. From my email to her:

> A 3 line example of the commands they would use would be:
>
> library(peditools)
> add_lmsdata(read.csv('fenton_2013.csv'))
> round(pnorm(x_to_z(c(493,589,792,992,1085), c(26,26,26,26,26), 'f', 'fenton_2013', 'weight')), 4)
>
> the first line loads the peditools R package (but without any private LMS data)
> the second line reads in the private LMS data locally from the 'fenton_2013.csv' file (that I've attached here)
> the third line is testing with a 26 0/7 week female with weights for the 3 / 10 / 50 / 90 / 97 percentiles
> The output of the last line should be: 0.0301 0.1002 0.5004 0.8997 0.9699
> But, if they did NOT run the 'add_lmsdata' line, they would get the error: Error: No chart / measure matched

Hope this helps!

**Comment by zxy1219** [comment]
The fenton_2013 is a chart for preterm infants. In your example, is the 26 0/7 a gestational age, postmenopausal age, or chronological age? If look at the weight values (the unit is grams?), the 26 0/7 looks like a gestational age.

**Comment by bajun65537** [comment]
Any updates on that? I've emailed Dr Tanis Fenton but got no response. I also second @zxy1219's question.

**Comment by jhchou** [comment]
> Any updates on that? I've emailed Dr Tanis Fenton but got no response.

Apologies, but I don't have permission or authority to distribute LMS parameters for Tanis Fenton's 2013 preterm growth chart. All I can suggest is continuing to attempt to contact her or her University / lawyers, who I believe handle the licensing arrangements. Beyond that, I'm not sure what to suggest.

> I also second @zxy1219's question.

The example simply shows that **if and ONLY if you have access to the fenton_2013.csv LMS parameters from Dr. Fenton**, using the **Fenton 2013's weight chart** for **female infants**, that if you input 26 weeks as the "age" parameter, what the percentiles would be for 293, 589, 792, 992, and 1085 grams. For me, with the LMS parameters available:

```
> library(peditools)
> add_lmsdata(fenton_2013_lmsdata)
> round(pnorm(x_to_z(c(493,589,792,992,1085), c(26,26,26,26,26), 'f', 'fenton_2013', 'weight')), 4)
[1] 0.0301 0.1002 0.5004 0.8997 0.9699
```

... which corresponds to the 3rd, 10th, 50th, 90th, and 97th percentiles respectively for those weights, at 26 0/7 weeks gestation.

The Olsen 2010 preterm growth charts ARE publicly available, so I included them in the PediTools R package. So if you were to run the same command, but specifying the included Olsen 2010 chart:

```
> round(pnorm(x_to_z(c(493,589,792,992,1085), c(26,26,26,26,26), 'f', 'olsen_2010', 'weight')), 4)
[1] 0.0138 0.0662 0.5110 0.9447 0.9904
```
... you can see the (probably inconsequential) differences between the percentiles of the Fenton 2013 and Olsen 2010 charts.

**Comment by bajun65537** [comment]
Thank you for the response. I think the issue's ready to be closed. 🚀
